title: Adjoa Kittoe
logo: /assets/img/logo.png
description:  Culinarian & Aspiring Full-Stack Developer 
description: >
  Culinarian & Aspiring Full-Stack Developer  
  <br>
  <br>
  <a href="https://www.instagram.com/seulful" target="_blank">ğŸ“· Instagram</a> 
  <br>
  <a href="https://github.com/akittoe" target="_blank">ğŸ’» Github</a>
  <br>
  <a href="https://www.linkedin.com/in/AdjoaKittoe" target="_blank">ğŸ“ LinkedIn</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
